service: expense-tracker-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ca-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    COGNITO_USER_POOL_CLIENT_ID: 6co59j70meatfn2u3964k6r8ns
    COGNITO_USER_POOL_ID: ca-central-1_uLrgknZWQ

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - "arn:aws:dynamodb:ca-central-1:*:table/ExpenseTrackerUsers"
            - "arn:aws:dynamodb:ca-central-1:*:table/ExpenseTrackerTransactions"
            - "arn:aws:dynamodb:ca-central-1:*:table/ExpenseTrackerTransactions/index/*"
            - "arn:aws:dynamodb:ca-central-1:*:table/ExpenseTrackerBudgets"
            - "arn:aws:dynamodb:ca-central-1:*:table/ExpenseTrackerBudgets/index/*"
            - "arn:aws:dynamodb:ca-central-1:*:table/ExpenseTrackerRecurringTransactions"
            - "arn:aws:dynamodb:ca-central-1:*:table/ExpenseTrackerRecurringTransactions/index/*"

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ExpenseTrackerUsers
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    TransactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ExpenseTrackerTransactions
        AttributeDefinitions:
          - AttributeName: transactionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: transactionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserDateIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    
    BudgetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ExpenseTrackerBudgets
        AttributeDefinitions:
          - AttributeName: budgetId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: month
            AttributeType: S
        KeySchema:
          - AttributeName: budgetId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserMonthIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: month
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    
    RecurringTransactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ExpenseTrackerRecurringTransactions
        AttributeDefinitions:
          - AttributeName: recurringId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: recurringId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserRecurringIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
